field: 1291907d-96e0-43f0-9cc4-daa2869d04dc # Menu
fieldLayouts:
  a730b451-b0e1-4172-b8ea-fe0dbc70983b:
    tabs:
      -
        elements:
          -
            fieldUid: d347ea3d-bb5d-47f2-8148-a8ba73e2c940 # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 02f6c616-acf7-492c-a46e-a6558ec33a1f # Url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  02f6c616-acf7-492c-a46e-a6558ec33a1f: # Url
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: itemUrl
    instructions: ''
    name: Url
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  d347ea3d-bb5d-47f2-8148-a8ba73e2c940: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: item
name: Item
sortOrder: 1
