field: ad4fee51-0e0c-4f8d-83d0-366aa74c639c # Tabs
fieldLayouts:
  342e710c-1549-495a-9533-2352b6202801:
    tabs:
      -
        elements:
          -
            fieldUid: c4465209-bcec-400f-abf2-c8133e127126 # Tab Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a6039a84-a2af-435b-8c36-5da10029aea9 # Tab Url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: de5d6326-237b-4ef6-942b-182c39caba73 # Tab Inactive
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a6039a84-a2af-435b-8c36-5da10029aea9: # Tab Url
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: tabUrl
    instructions: ''
    name: 'Tab Url'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  c4465209-bcec-400f-abf2-c8133e127126: # Tab Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: tabTitle
    instructions: ''
    name: 'Tab Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  de5d6326-237b-4ef6-942b-182c39caba73: # Tab Inactive
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: tabInactive
    instructions: ''
    name: 'Tab Inactive'
    searchable: false
    settings:
      default: true
      offLabel: Inactive
      onLabel: Active
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: tab
name: Tab
sortOrder: 1
