fieldLayouts:
  48a09bd2-52e7-4a33-99a8-16d7eef95c22:
    tabs:
      -
        elements:
          -
            fieldUid: fe109994-56db-4b6b-bc22-e06154620dd1 # Menu Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Home Page Fields'
        sortOrder: 1
handle: homePage
hasTitleField: false
name: 'Home Page'
section: 4327d63d-c0a9-4461-afc5-a80427aa7450 # Home Page
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
