columnSuffix: ebuzbyye
contentColumnType: string(255)
fieldGroup: 9baab332-2b61-4668-81ac-7ad4c612bb2a # Home Page
handle: contentRightLinkUrl
instructions: ''
name: 'Content Right Link Url'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
