columnSuffix: null
contentColumnType: string
fieldGroup: 5206c881-23d6-452b-805c-6c38e1abf02b # Whisky Fields
handle: image
instructions: ''
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:50f68bc7-5e17-4607-a4c1-86e383650bae' # Whiskies
  defaultUploadLocationSubpath: ''
  limit: '5'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:50f68bc7-5e17-4607-a4c1-86e383650bae' # Whiskies
  singleUploadLocationSubpath: whiskies
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
