columnSuffix: istxxtnt
contentColumnType: text
fieldGroup: 9baab332-2b61-4668-81ac-7ad4c612bb2a # Home Page
handle: introHeading
instructions: ''
name: 'Intro Heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
