dateModified: 1644004367
email:
  fromEmail: admin@example.com
  fromName: Whiskygalore
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5ef406da-704a-42c7-b797-0e563f48d8ff: 'Link Text' # Link Text
    012ecc82-b3da-4f9f-872a-4bb1db3688a7: Common # Common
    50f68bc7-5e17-4607-a4c1-86e383650bae: Whiskies # Whiskies
    302e9976-9095-4e4a-934d-0f370e896e96: Image # Image
    350c6d93-dcf2-4b64-a171-c3523f053b95: 'Public Schema' # Public Schema
    725b346c-6c19-4d8c-9ec5-830f2633f810: Link # Link
    805b7fa7-1af5-46cc-8ed5-de97073e0697: Whisky # Whisky
    1365aec2-cd53-477d-9ac3-0ff6074c7872: Text # Text
    3640a29c-41e4-4f8c-9cce-73367dbb8fff: Image # Image
    4327d63d-c0a9-4461-afc5-a80427aa7450: 'Home Page' # Home Page
    5206c881-23d6-452b-805c-6c38e1abf02b: 'Whisky Fields' # Whisky Fields
    8974a40c-bd8a-4d16-b5d9-08097d782264: Image # Image
    40596ee9-5916-4c79-b2d6-2e0fd9b252d4: Description # Description
    131717ab-4367-46ad-8212-caaa95a565c5: 'Link Destination' # Link Destination
    ab4973fd-7516-44ce-a308-b224f9af0c9f: Whiskygalore # Whiskygalore
    b0a171ce-aa59-4111-a302-3da7ef50f706: 'Home Page' # Home Page
    d1e8755c-91e1-4d32-bf27-f8588feae365: Text # Text
    d75d86bd-f9a4-4ed1-a49a-06f3d7081b26: Whiskygalore # Whiskygalore
    f929aaa4-a6f9-49b1-9b31-90018bf1b7cd: Whiskies # Whiskies
    fe109994-56db-4b6b-bc22-e06154620dd1: 'Menu Links' # Menu Links
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  whisky-json:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      endpoint: whisky-json
system:
  edition: pro
  live: true
  name: Whiskygalore
  retryDuration: null
  schemaVersion: 3.7.8
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
